[package]
name = "libflate"
version = "0.1.24"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "A Rust implementation of DEFLATE algorithm and related formats (ZLIB, GZIP)"
homepage = "https://github.com/sile/libflate"
repository = "https://github.com/sile/libflate"
readme = "README.md"
keywords = ["deflate", "gzip", "zlib"]
categories = ["compression"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/libflate"}
codecov = {repository = "sile/libflate"}

[dependencies]
adler32 = "1"
byteorder = "1"
crc32fast = "1"
rle-decode-fast = "1.0.0"
take_mut = "0.2.2"

[dev-dependencies]
clap = "2"
